interface classTheme {
    [key: number]: {
        id: number,
        img: string,
        deepColor: string,
        deepColor2: string,
        lightColor: string,
        lightColor2: string,
    }
}
const $classTheme: classTheme = {
    1: {
        // blue
        id: 1,
        img: "/image/cover/blue-sms.jpg",
        deepColor: "#3367D4",
        deepColor2: "#3367D4",
        lightColor: "#ebf0fb",
        lightColor2: "#ebf0fb",
    },
    2: {
        // pink,
        id: 2,
        img: "/image/cover/pink.jpg",
        deepColor: "#D91A60",
        deepColor2: "#D91A60",
        lightColor: "#fce7ef",
        lightColor2: "#fce7ef",
    },
    3: {
        // green,
        id: 3,
        img: "/image/cover/green-books.jpg",
        deepColor: "rgb(22 163 74)",
        deepColor2: "rgb(22 163 74)",
        lightColor: "#e9f8f1",
        lightColor2: "#e9f8f1",
    },
    4: {
        // violet,
        id: 4,
        img: "/image/cover/violet-laptop.jpg",
        deepColor: "#775BA5",
        deepColor2: "#775BA5",
        lightColor: "#f1eff6",
        lightColor2: "#f1eff6",
    },
    5: {
        // gray,
        id: 5,
        img: "/image/cover/read.jpg",
        deepColor: "#566E7A",
        deepColor2: "#566E7A",
        lightColor: "#edf1f2",
        lightColor2: "#edf1f2",
    },
    6: {
        // blue,
        id: 6,
        img: "/image/cover/blue-magnet.jpg",
        deepColor: "#4167B2",
        deepColor2: "#4167B2",
        lightColor: "#ebf0f8",
        lightColor2: "#ebf0f8",
    },
    7: {
        // violet,
        id: 7,
        img: "/image/cover/chemistry.jpg",
        deepColor: "#853A94",
        deepColor2: "#853A94",
        lightColor: "#f4e9f6",
        lightColor2: "#f4e9f6",
    },
    8: {
        // pink,
        id: 8,
        img: "/image/cover/pink.jpg",
        deepColor: "#D91A60",
        deepColor2: "#D91A60",
        lightColor: "#fce7ef",
        lightColor2: "#fce7ef",
    },
    9: {
        // blue,
        id: 9,
        img: "/image/cover/school-bag.jpg",
        deepColor: "#0277BD",
        deepColor2: "#0277BD",
        lightColor: "#dff3ff",
        lightColor2: "#dff3ff",
    },
    10: {
        // blue,
        id: 10,
        img: "/image/cover/history.jpg",
        deepColor: "#3E4DA1",
        deepColor2: "#3E4DA1",
        lightColor: "#eaecf7",
        lightColor2: "#eaecf7",
    },
    11: {
        // cyan,
        id: 11,
        img: "/image/cover/green-pest.jpg",
        deepColor: "#0C8590",
        deepColor2: "#0C8590",
        lightColor: "#defafc",
        lightColor2: "#defafc",
    },
    12: {
        // dark gray, 
        id: 12,
        img: "/image/cover/honors.jpg",
        deepColor: "#36474F",
        deepColor2: "#36474F",
        lightColor: "#e9edf0",
        lightColor2: "#e9edf0",
    }
};

export default $classTheme;